name: Ritchie Bros QA tests on Dockers

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Create videos folder
        run: mkdir -p videos

      - name: Start Grid
        run: docker compose up -d

      - name: Run Tests
        run: mvn clean test -Pui-tests

      - name: Upload Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: target/surefire-reports/

      - name: Stop Grid
        run: docker compose down

      - name: Wait for video file
        run: sleep 5

      - name: Check videos
        run: ls -R videos

      - name: Upload Videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: selenium-videos
          path: videos/